[2025-06-12T18:52:20.611+0000] {processor.py:186} INFO - Started process (PID=54) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:52:20.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:52:20.639+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:52:20.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:52:20.692+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:52:20.710+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:52:20.711+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:52:20.712+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:52:20.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.271 seconds
[2025-06-12T18:52:51.157+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:52:51.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:52:51.182+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:52:51.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:52:51.224+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:52:51.233+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:52:51.233+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:52:51.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:52:51.274+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.136 seconds
[2025-06-12T18:53:21.573+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:53:21.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:53:21.583+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:53:21.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:53:21.611+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:53:21.618+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:53:21.622+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:53:21.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:53:21.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.097 seconds
[2025-06-12T18:53:52.003+0000] {processor.py:186} INFO - Started process (PID=132) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:53:52.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:53:52.012+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:53:52.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:53:52.036+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:53:52.042+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:53:52.043+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:53:52.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:53:52.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.093 seconds
[2025-06-12T18:54:22.367+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:54:22.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:54:22.373+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:54:22.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:54:22.402+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:54:22.408+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:54:22.409+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:54:22.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:54:22.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.086 seconds
[2025-06-12T18:54:52.703+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:54:52.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:54:52.712+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:54:52.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:54:52.742+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:54:52.750+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:54:52.750+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:54:52.752+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:54:52.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.091 seconds
[2025-06-12T18:55:23.251+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:55:23.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:55:23.267+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:55:23.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:55:23.295+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:55:23.302+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:55:23.303+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:55:23.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:55:23.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.117 seconds
[2025-06-12T18:55:53.656+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:55:53.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:55:53.667+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:55:53.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:55:53.689+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:55:53.695+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:55:53.696+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:55:53.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:55:53.727+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.087 seconds
[2025-06-12T18:56:24.036+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:56:24.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:56:24.046+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:56:24.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:56:24.073+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:56:24.083+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:56:24.083+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:56:24.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:56:24.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.098 seconds
[2025-06-12T18:56:54.447+0000] {processor.py:186} INFO - Started process (PID=298) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:56:54.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:56:54.455+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:56:54.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:56:54.499+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:56:54.505+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:56:54.506+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:56:54.509+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:56:54.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.109 seconds
[2025-06-12T18:57:25.011+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:57:25.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:57:25.021+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:57:25.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:57:25.051+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:57:25.057+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:57:25.058+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:57:25.059+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:57:25.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.097 seconds
[2025-06-12T18:57:55.482+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:57:55.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:57:55.490+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:57:55.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:57:55.519+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:57:55.526+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:57:55.526+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:57:55.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:57:55.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.094 seconds
[2025-06-12T18:58:25.923+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:58:25.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:58:25.931+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:58:25.930+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:58:25.963+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:58:25.969+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:58:25.970+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:58:25.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:58:25.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.093 seconds
[2025-06-12T18:58:56.224+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:58:56.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:58:56.232+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:58:56.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:58:56.259+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:58:56.264+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:58:56.265+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:58:56.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:58:56.291+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.082 seconds
[2025-06-12T18:59:26.668+0000] {processor.py:186} INFO - Started process (PID=444) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:59:26.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:59:26.675+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:59:26.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:59:26.705+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:59:26.713+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:59:26.714+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:59:26.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:59:26.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.094 seconds
[2025-06-12T18:59:57.106+0000] {processor.py:186} INFO - Started process (PID=470) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:59:57.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T18:59:57.116+0000] {logging_mixin.py:190} INFO - [2025-06-12T18:59:57.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:59:57.141+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T18:59:57.147+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T18:59:57.147+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T18:59:57.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T18:59:57.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.088 seconds
[2025-06-12T19:00:27.552+0000] {processor.py:186} INFO - Started process (PID=496) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:00:27.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:00:27.560+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:00:27.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:00:27.591+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:00:27.597+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:00:27.598+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:00:27.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:00:27.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.088 seconds
[2025-06-12T19:00:57.885+0000] {processor.py:186} INFO - Started process (PID=531) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:00:57.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:00:57.895+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:00:57.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:00:57.924+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:00:57.931+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:00:57.932+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:00:57.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:00:57.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.106 seconds
[2025-06-12T19:01:28.351+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:01:28.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:01:28.361+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:01:28.360+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:01:28.412+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:01:28.423+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:01:28.423+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:01:28.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:01:28.459+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.132 seconds
[2025-06-12T19:01:58.949+0000] {processor.py:186} INFO - Started process (PID=583) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:01:58.951+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:01:58.957+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:01:58.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:01:58.991+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:01:58.998+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:01:58.999+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:01:59.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:01:59.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.106 seconds
[2025-06-12T19:02:29.370+0000] {processor.py:186} INFO - Started process (PID=619) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:02:29.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:02:29.380+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:02:29.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:02:29.409+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:02:29.415+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:02:29.416+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:02:29.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:02:29.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.106 seconds
[2025-06-12T19:02:59.853+0000] {processor.py:186} INFO - Started process (PID=645) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:02:59.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:02:59.863+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:02:59.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:02:59.894+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:02:59.901+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:02:59.901+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:02:59.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:02:59.931+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.104 seconds
[2025-06-12T19:03:30.277+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:03:30.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:03:30.286+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:03:30.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:03:30.320+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:03:30.327+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:03:30.328+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:03:30.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:03:30.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.110 seconds
[2025-06-12T19:04:00.734+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:04:00.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:04:00.744+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:04:00.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:04:00.777+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:04:00.785+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:04:00.786+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:04:00.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:04:00.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.105 seconds
[2025-06-12T19:04:31.198+0000] {processor.py:186} INFO - Started process (PID=723) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:04:31.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:04:31.209+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:04:31.208+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:04:31.243+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:04:31.249+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:04:31.250+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:04:31.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:04:31.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.109 seconds
[2025-06-12T19:05:01.717+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:05:01.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:05:01.726+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:05:01.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:05:01.761+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:05:01.768+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:05:01.769+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:05:01.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:05:01.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.112 seconds
[2025-06-12T19:05:32.190+0000] {processor.py:186} INFO - Started process (PID=784) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:05:32.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:05:32.199+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:05:32.199+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:05:32.236+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:05:32.244+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:05:32.245+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:05:32.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:05:32.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.113 seconds
[2025-06-12T19:06:02.687+0000] {processor.py:186} INFO - Started process (PID=810) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:06:02.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:06:02.697+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:06:02.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:06:02.727+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:06:02.734+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:06:02.734+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:06:02.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:06:02.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.100 seconds
[2025-06-12T19:06:33.154+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:06:33.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:06:33.164+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:06:33.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:06:33.195+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:06:33.204+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:06:33.205+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:06:33.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:06:33.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.105 seconds
[2025-06-12T19:07:03.553+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:07:03.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:07:03.561+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:07:03.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:07:03.592+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:07:03.598+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:07:03.599+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:07:03.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:07:03.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.096 seconds
[2025-06-12T19:07:34.198+0000] {processor.py:186} INFO - Started process (PID=904) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:07:34.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:07:34.206+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:07:34.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:07:34.232+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:07:34.238+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:07:34.239+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:07:34.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:07:34.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.089 seconds
[2025-06-12T19:08:04.664+0000] {processor.py:186} INFO - Started process (PID=930) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:08:04.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:08:04.674+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:08:04.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:08:04.701+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:08:04.707+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:08:04.708+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:08:04.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:08:04.740+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.109 seconds
[2025-06-12T19:08:35.070+0000] {processor.py:186} INFO - Started process (PID=956) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:08:35.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:08:35.080+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:08:35.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:08:35.113+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:08:35.120+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:08:35.121+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:08:35.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:08:35.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.104 seconds
[2025-06-12T19:09:48.906+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:09:48.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:09:48.916+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:09:48.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:09:48.945+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:09:48.962+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:09:48.963+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:09:48.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:09:49.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.154 seconds
[2025-06-12T19:10:19.413+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:10:19.416+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:10:19.424+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:10:19.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:10:19.455+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:10:19.462+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:10:19.463+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:10:19.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:10:19.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.100 seconds
[2025-06-12T19:10:49.806+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:10:49.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:10:49.814+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:10:49.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:10:49.859+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:10:49.878+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:10:49.880+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:10:49.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:10:49.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.171 seconds
[2025-06-12T19:11:20.332+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:11:20.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:11:20.344+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:11:20.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:11:20.370+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:11:20.376+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:11:20.376+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:11:20.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:11:20.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.094 seconds
[2025-06-12T19:11:50.750+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:11:50.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:11:50.757+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:11:50.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:11:50.786+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:11:50.794+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:11:50.795+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:11:50.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:11:50.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.092 seconds
[2025-06-12T19:12:21.111+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:12:21.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:12:21.122+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:12:21.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:12:21.172+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:12:21.181+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:12:21.182+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:12:21.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:12:21.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.125 seconds
[2025-06-12T19:12:51.489+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:12:51.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:12:51.499+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:12:51.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:12:51.524+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:12:51.530+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:12:51.531+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:12:51.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:12:51.558+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.085 seconds
[2025-06-12T19:13:21.869+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:13:21.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:13:21.880+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:13:21.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:13:21.911+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:13:21.920+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:13:21.921+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:13:21.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:13:21.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.113 seconds
[2025-06-12T19:13:52.301+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:13:52.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:13:52.309+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:13:52.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:13:52.337+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:13:52.344+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:13:52.345+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:13:52.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:13:52.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.092 seconds
[2025-06-12T19:14:22.658+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:14:22.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:14:22.665+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:14:22.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:14:22.695+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:14:22.703+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:14:22.704+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:14:22.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:14:22.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.089 seconds
[2025-06-12T19:14:53.216+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:14:53.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:14:53.224+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:14:53.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:14:53.250+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:14:53.257+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:14:53.258+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:14:53.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:14:53.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.088 seconds
[2025-06-12T19:15:23.595+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:15:23.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:15:23.606+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:15:23.605+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:15:23.634+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:15:23.641+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:15:23.641+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:15:23.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:15:23.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.107 seconds
[2025-06-12T19:15:54.044+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:15:54.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:15:54.055+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:15:54.055+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:15:54.089+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:15:54.096+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:15:54.097+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:15:54.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:15:54.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.117 seconds
[2025-06-12T19:16:24.527+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:16:24.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:16:24.536+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:16:24.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:16:24.561+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:16:24.569+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:16:24.570+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:16:24.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:16:24.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.099 seconds
[2025-06-12T19:16:54.910+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:16:54.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:16:54.916+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:16:54.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:16:54.948+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:16:54.956+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:16:54.958+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:16:54.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:16:54.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.091 seconds
[2025-06-12T19:17:25.258+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:17:25.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:17:25.266+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:17:25.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:17:25.291+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:17:25.297+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:17:25.297+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:17:25.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:17:25.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.088 seconds
[2025-06-12T19:17:55.688+0000] {processor.py:186} INFO - Started process (PID=499) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:17:55.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:17:55.704+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:17:55.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:17:55.749+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:17:55.760+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:17:55.761+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:17:55.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:17:55.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.188 seconds
[2025-06-12T19:18:26.415+0000] {processor.py:186} INFO - Started process (PID=525) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:18:26.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:18:26.428+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:18:26.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:18:26.465+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:18:26.473+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:18:26.474+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:18:26.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:18:26.510+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.130 seconds
[2025-06-12T19:18:56.925+0000] {processor.py:186} INFO - Started process (PID=551) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:18:56.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:18:56.931+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:18:56.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:18:56.959+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:18:56.965+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:18:56.966+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:18:56.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:18:56.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.085 seconds
[2025-06-12T19:19:27.299+0000] {processor.py:186} INFO - Started process (PID=586) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:19:27.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:19:27.312+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:19:27.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:19:27.340+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:19:27.348+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:19:27.349+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:19:27.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:19:27.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.100 seconds
[2025-06-12T19:19:57.862+0000] {processor.py:186} INFO - Started process (PID=612) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:19:57.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:19:57.876+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:19:57.875+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:19:57.913+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:19:57.926+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:19:57.927+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:19:57.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:19:57.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.126 seconds
[2025-06-12T19:20:28.206+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:20:28.209+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:20:28.214+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:20:28.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:20:28.270+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:20:28.278+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:20:28.278+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:20:28.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:20:28.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.129 seconds
[2025-06-12T19:20:58.534+0000] {processor.py:186} INFO - Started process (PID=665) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:20:58.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:20:58.542+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:20:58.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:20:58.570+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:20:58.577+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:20:58.578+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:20:58.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:20:58.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.089 seconds
[2025-06-12T19:21:28.937+0000] {processor.py:186} INFO - Started process (PID=691) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:21:28.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:21:28.945+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:21:28.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:21:28.966+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:21:28.972+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:21:28.972+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:21:28.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:21:28.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.079 seconds
[2025-06-12T19:21:59.344+0000] {processor.py:186} INFO - Started process (PID=725) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:21:59.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:21:59.354+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:21:59.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:21:59.389+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:21:59.395+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:21:59.396+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:21:59.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:21:59.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.105 seconds
[2025-06-12T19:22:29.822+0000] {processor.py:186} INFO - Started process (PID=752) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:22:29.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:22:29.828+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:22:29.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:22:29.858+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:22:29.865+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:22:29.866+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:22:29.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:22:29.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.094 seconds
[2025-06-12T19:23:00.322+0000] {processor.py:186} INFO - Started process (PID=778) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:23:00.324+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:23:00.327+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:23:00.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:23:00.357+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:23:00.363+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:23:00.364+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:23:00.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:23:00.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.080 seconds
[2025-06-12T19:23:30.633+0000] {processor.py:186} INFO - Started process (PID=804) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:23:30.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:23:30.643+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:23:30.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:23:30.670+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:23:30.677+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:23:30.678+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:23:30.679+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:23:30.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.096 seconds
[2025-06-12T19:31:33.296+0000] {processor.py:186} INFO - Started process (PID=52) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:31:33.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:31:33.302+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:31:33.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:31:33.328+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:31:33.342+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:31:33.343+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:31:33.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:31:33.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.091 seconds
[2025-06-12T19:32:03.754+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:32:03.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:32:03.761+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:32:03.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:32:03.791+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:32:03.798+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:32:03.799+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:32:03.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:32:03.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.110 seconds
[2025-06-12T19:32:33.998+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:32:34.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:32:34.008+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:32:34.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:32:34.039+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:32:34.046+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:32:34.047+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:32:34.048+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:32:34.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.100 seconds
[2025-06-12T19:33:04.389+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:33:04.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:33:04.405+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:33:04.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:33:04.443+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:33:04.454+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:33:04.455+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:33:04.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:33:04.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.166 seconds
[2025-06-12T19:33:34.908+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:33:34.914+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:33:34.926+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:33:34.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:33:34.965+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:33:34.976+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:33:34.977+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:33:34.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:33:35.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.120 seconds
[2025-06-12T19:34:05.349+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:34:05.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:34:05.358+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:34:05.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:34:05.390+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:34:05.399+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:34:05.399+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:34:05.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:34:05.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.094 seconds
[2025-06-12T19:34:35.716+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:34:35.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:34:35.725+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:34:35.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:34:35.750+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:34:35.757+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:34:35.758+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:34:35.759+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:34:35.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.087 seconds
[2025-06-12T19:35:06.194+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:35:06.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:35:06.202+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:35:06.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:35:06.234+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:35:06.242+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:35:06.243+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:35:06.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:35:06.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.087 seconds
[2025-06-12T19:35:36.566+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:35:36.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:35:36.571+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:35:36.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:35:36.599+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:35:36.605+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:35:36.606+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:35:36.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:35:36.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.075 seconds
[2025-06-12T19:36:07.076+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:36:07.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:36:07.087+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:36:07.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:36:07.122+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:36:07.129+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:36:07.129+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:36:07.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:36:07.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.111 seconds
[2025-06-12T19:36:37.505+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:36:37.506+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:36:37.511+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:36:37.511+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:36:37.537+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:36:37.543+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:36:37.544+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:36:37.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:36:37.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.081 seconds
[2025-06-12T19:37:07.910+0000] {processor.py:186} INFO - Started process (PID=363) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:37:07.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:37:07.918+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:37:07.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:37:07.945+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:37:07.952+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:37:07.953+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:37:07.954+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:37:07.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.085 seconds
[2025-06-12T19:37:38.214+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:37:38.216+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:37:38.223+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:37:38.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:37:38.251+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:37:38.260+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:37:38.261+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:37:38.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:37:38.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.085 seconds
[2025-06-12T19:38:08.685+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:38:08.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:38:08.692+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:38:08.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:38:08.725+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:38:08.734+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:38:08.735+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:38:08.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:38:08.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.110 seconds
[2025-06-12T19:38:39.281+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:38:39.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/2nd_dag.py for tasks to queue
[2025-06-12T19:38:39.302+0000] {logging_mixin.py:190} INFO - [2025-06-12T19:38:39.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:38:39.461+0000] {logging_mixin.py:190} INFO - ERROR: Failed to import scripts.etl_processor at DAG parse time: No module named 'scripts.etl_processor'
[2025-06-12T19:38:39.510+0000] {logging_mixin.py:190} INFO - Traceback (most recent call last):
  File "/opt/airflow/dags/2nd_dag.py", line 19, in <module>
    from scripts.etl_processor import load_static_data_to_redshift_task, process_stream_data_task
ModuleNotFoundError: No module named 'scripts.etl_processor'
[2025-06-12T19:38:39.511+0000] {logging_mixin.py:190} INFO - DAG 'initial_static_data_load_dag' not defined due to import error.
[2025-06-12T19:38:39.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/2nd_dag.py
[2025-06-12T19:38:39.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/2nd_dag.py took 0.327 seconds
